weather_in_city:
    path: /weather/{city}
    controller: App\Controller\WeatherController:cityAction
    defaults:
        city: 1
    requirements:
        ciy: \d+
weather_by_name:
    path: /weather-name/{name}
    controller: App\Controller\WeatherController:cityActionByName
 

